/**
 * TODAY — Scenario N: the One Move presentation lifecycle, and what actually exists for every registered
 * target kind (Addendum §N: "if a target kind has no legitimate completion affordance, do not manufacture one").
 */
import assert from 'node:assert/strict';
import { describe, test } from 'node:test';
import { completeOneMove, oneMoveRecordId, resolveOneMoveForToday } from '../../src/domain/oneMove.ts';
import { addPerson, delegate } from '../../src/domain/responsibility.ts';
import { ONE_MOVE_TARGET_TYPES } from '../../src/domain/state.ts';
import { captureNeedsMeItem } from '../../src/domain/needsMe.ts';
import { demoState, onboardedState } from '../support/fixtures.mjs';
import { SYSTEM, USER } from '../support/provenance.mjs';
import { DAY, NEXT_DAY, at, ev, eventNamed, household, mkCtx, nyInstant, nyMs, taskNamed, tk, valid, view, withMove } from './fixtures.mjs';

const keys = (v) => v.composition.map((c) => c.key);

describe('Scenario N — One Move lifecycle', () => {
  test('NO DECISION YET: nothing stored for the day renders nothing — not a filler card, not a guess', () => {
    const v = view(valid(household()), nyMs(9));
    assert.equal(v.oneMove, null);
    assert.equal(keys(v).includes('oneMove'), false);
  });

  test('SELECTED: a recommendation with a target that resolves, a reason, and a truthful completion effect', () => {
    const state = withMove(valid(tk(household(), { title: 'Renew library card', minutes: 15 })));
    const m = view(state, nyMs(9)).oneMove;
    assert.deepEqual([m.status, m.action, m.targetType], ['selected', 'Renew library card', 'task']);
    assert.equal(m.targetId, taskNamed(state, 'Renew library card').id);
    assert.ok(m.why.reasons.length > 0);
    assert.equal(m.completion, 'completes_task');
  });

  test('COMPLETED: renders truthfully, asks for nothing, and the finished task no longer demands anything', () => {
    let state = withMove(valid(tk(tk(household(), { title: 'Renew library card', minutes: 15 }), { title: 'Order sneakers', minutes: 20 })));
    state = completeOneMove(state, mkCtx(nyMs(9)));
    const v = view(state, nyMs(9, 5));
    assert.deepEqual([v.oneMove.status, v.oneMove.completion, v.oneMove.why], ['completed', null, null]);
    assert.equal(v.matters, null);
    assert.equal(v.canWait?.items.some((i) => i.title === 'Renew library card') ?? false, false);
    assert.equal(taskNamed(state, 'Renew library card').status, 'completed');
    assert.equal(state.oneMoves.length, 1, 'no replacement move is generated merely because one was completed');
  });

  test('WITHHELD: a deliberate rest is not "no data", and no other move is manufactured to fill the space', () => {
    let s = household();
    s = ev(s, { title: 'Work call', from: [15], to: [16, 30], category: 'cat-work' });
    s = ev(s, { title: 'Soccer practice', from: [17], to: [18, 30] });
    s = tk(s, { title: 'Prep dinner', minutes: 40, plan: { kind: 'timed', startsAt: at(16, 30) } });
    const state = withMove(valid(s));
    assert.equal(state.oneMoves[0].status, 'withheld');
    const m = view(state, nyMs(14)).oneMove;
    assert.deepEqual([m.status, m.action, m.targetId, m.why, m.completion], ['withheld', null, null, null, null]);
  });

  test('LOGICAL-DAY ROLLOVER: yesterday’s completed (or selected) move is not today’s, and none is generated by looking', () => {
    // Planned for today AND due tomorrow, so the second is still on tomorrow's radar (a day-plan alone would not carry over).
    let state = withMove(valid(tk(tk(household(), { title: 'Renew library card', minutes: 15, due: NEXT_DAY }), { title: 'Order sneakers', minutes: 20, due: NEXT_DAY })));
    state = completeOneMove(state, mkCtx(nyMs(9)));
    const before = JSON.stringify(state.oneMoves);

    const morning = view(state, nyMs(8, 0, 17));
    assert.equal(morning.day.date, NEXT_DAY);
    assert.equal(morning.oneMove, null, 'yesterday’s completed move does not become today’s');
    assert.equal(JSON.stringify(state.oneMoves), before, 'the projection wrote nothing');

    const decided = resolveOneMoveForToday(state, mkCtx(nyMs(8, 0, 17), NEXT_DAY));
    const next = view(decided, nyMs(8, 0, 17)).oneMove;
    assert.equal(next.status, 'selected');
    assert.equal(next.action, 'Order sneakers', 'the next day decides afresh — and never re-offers what was done');
  });

  test('an unfinished move from yesterday is not carried forward either', () => {
    const state = withMove(valid(tk(household(), { title: 'Renew library card', minutes: 15 })));
    assert.equal(view(state, nyMs(9)).oneMove.status, 'selected');
    assert.equal(view(state, nyMs(9, 0, 17)).oneMove, null);
  });
});

describe('Scenario N — every registered target kind: what exists, and only what exists', () => {
  const record = (state, targetType, targetId) =>
    valid({ ...state, oneMoves: [{ id: oneMoveRecordId(DAY), forDate: DAY, targetId, targetType, status: 'selected', decidedAt: nyInstant(7), completedAt: null, provenance: SYSTEM, scope: 'personal' }] });

  const builders = {
    catalog: () => ({ state: onboardedState(demoState()), expect: { open: null, completion: 'records_only' } }),
    task: () => {
      const s = tk(household(), { title: 'Renew library card' });
      const t = taskNamed(s, 'Renew library card');
      return { state: record(s, 'task', t.id), expect: { open: { pathname: '/task-editor', params: { taskId: t.id } }, completion: 'completes_task' } };
    },
    needsMe: () => {
      const s = captureNeedsMeItem(household(), mkCtx(), { title: 'Renew passport' });
      return { state: record(s, 'needsMe', s.needsMe[0].id), expect: { open: { pathname: '/life/needs-me' }, completion: 'resolves_needs_me' } };
    },
    event: () => {
      const s = ev(household(), { title: 'Parent conference', from: [16], to: [17] });
      const e = eventNamed(s, 'Parent conference');
      return { state: record(s, 'event', e.id), expect: { open: { pathname: '/event-editor', params: { eventId: e.id } }, completion: 'records_only' }, action: 'Parent conference' };
    },
    system: () => {
      const s = {
        ...household(),
        systems: [{ id: 'sys-1', name: 'Sunday reset', description: 'Reset the house for the week', categoryId: 'cat-home', automationMode: 'manual', effortMinutes: 20, energyDemand: null, provenance: USER, scope: 'household' }],
      };
      return { state: record(s, 'system', 'sys-1'), expect: { open: null, completion: 'records_only' }, action: 'Sunday reset' };
    },
    responsibility: () => {
      let s = tk(household(), { title: 'Pack the field-trip bag' });
      s = addPerson(s, mkCtx(), { displayName: 'Dad', relationship: 'other' });
      s = delegate(s, mkCtx(), { about: { kind: 'task', id: taskNamed(s, 'Pack the field-trip bag').id }, to: { kind: 'person', id: s.people[0].id } });
      return { state: record(s, 'responsibility', s.responsibilities[0].id), expect: { open: null, completion: 'records_only' }, action: 'Check that this is covered' };
    },
  };

  test('the table covers exactly the registered kinds — a new kind cannot pass unexamined', () => {
    assert.deepEqual(Object.keys(builders).sort(), [...ONE_MOVE_TARGET_TYPES].sort());
  });

  for (const kind of ONE_MOVE_TARGET_TYPES) {
    test(`${kind}: open route and completion effect are exactly what the domain supports`, () => {
      const { state, expect, action } = builders[kind]();
      const m = view(state, nyMs(9)).oneMove;
      assert.equal(m.status, 'selected');
      assert.equal(m.targetType, kind);
      assert.deepEqual(m.open, expect.open);
      assert.equal(m.completion, expect.completion);
      if (action) assert.equal(m.action, action);
    });
  }

  test('a `records_only` kind really does nothing else: an event is not "completed" by "I did it"', () => {
    const { state } = builders.event();
    const event = state.events[0];
    const done = completeOneMove(state, mkCtx(nyMs(16, 30)));
    assert.equal(done.oneMoves[0].status, 'completed');
    assert.deepEqual(done.events[0], event, 'the event is untouched');
  });

  test('a kind that completes a row really does: a task is completed, a Needs Me item is resolved', () => {
    const task = builders.task().state;
    assert.equal(completeOneMove(task, mkCtx(nyMs(9))).tasks[0].status, 'completed');
    const nm = builders.needsMe().state;
    assert.equal(completeOneMove(nm, mkCtx(nyMs(9))).needsMe[0].status, 'resolved');
  });

  test('the demo catalog move keeps its own observation as the reason — no evidence is invented for it', () => {
    const m = view(builders.catalog().state, nyMs(9)).oneMove;
    assert.equal(m.why.basis, 'item_observation');
    assert.deepEqual(m.why.evidence, []);
    assert.equal(m.source, null, 'a catalog move has no row behind it, so no provenance is claimed');
  });
});
